USE OGRENCI_BILGI_SISTEMI_DUYURU_VERITABANI;

DELETE FROM DUYURUCU;
DELETE FROM OGRENCI_ISLERI_DUYURUCUSU;
DELETE FROM FAKULTE;
DELETE FROM BOLUM;
DELETE FROM BOLUM_DUYURUCUSU;
DELETE FROM FAKULTE_DUYURUCUSU;
DELETE FROM DUYURU;
DELETE FROM YONELIK;

DROP TABLE FAKULTE;
DROP TABLE BOLUM;
DROP TABLE OGRENCI_ISLERI_DUYURUCUSU;
DROP TABLE BOLUM_DUYURUCUSU;
DROP TABLE FAKULTE_DUYURUCUSU;
DROP TABLE DUYURUCU;
DROP TABLE DUYURU;
DROP TABLE YONELIK;

DROP TRIGGER DISJOINT_BOLUM_DUYURUCUSU;	
DROP TRIGGER DISJOINT_FAKULTE_DUYURUCUSU;
DROP TRIGGER DISJOINT_OGRENCI_ISLERI_DUYURUCUSU;
DROP TRIGGER DUYURAN_KISI_YETKILI_MI;
DROP TRIGGER GONDERILEN_BOLUMLERE_UYGUNLUK_KONTROLU;
DROP TRIGGER GONDERILEN_FAKULTELERE_UYGUNLUK_KONTROLU;