USE OGRENCI_BILGI_SISTEMI_DUYURU_VERITABANI;

SELECT * 
FROM DUYURU
INNER JOIN YONELIK ON YONELIK.Duyuru_id=DUYURU.Duyuru_id
WHERE YONELIK.Bolum_ismi='Bilgisayar Mühendisliði'

SELECT * 
FROM DUYURU
INNER JOIN YONELIK ON YONELIK.Duyuru_id=DUYURU.Duyuru_id
WHERE YONELIK.Fakulte_ismi='Mühendislik Fakültesi'

SELECT *
FROM DUYURUCU
WHERE DUYURUCU.Kimlik_numarasi='' AND DUYURUCU.Sifre=''

SELECT *
FROM YONELIK
INNER JOIN DUYURU ON YONELIK.Duyuru_id=DUYURU.Duyuru_id
INNER JOIN DUYURUCU ON DUYURUCU.Kimlik_numarasi=DUYURU.Kimlik_numarasi
INNER JOIN BOLUM_DUYURUCUSU ON BOLUM_DUYURUCUSU.Kimlik_numarasi=DUYURUCU.Kimlik_numarasi
WHERE BOLUM_DUYURUCUSU.Bolum_ismi != YONELIK.Bolum_ismi OR YONELIK.Fakulte_ismi IS NOT NULL

SELECT BOLUM_DUYURUCUSU.Bolum_ismi
FROM DUYURUCU
INNER JOIN BOLUM_DUYURUCUSU ON BOLUM_DUYURUCUSU.Kimlik_numarasi=DUYURUCU.Kimlik_numarasi

UNION ALL

SELECT FAKULTE_DUYURUCUSU.Fakulte_ismi 
FROM DUYURUCU
INNER JOIN FAKULTE_DUYURUCUSU ON FAKULTE_DUYURUCUSU.Kimlik_numarasi=DUYURUCU.Kimlik_numarasi

UNION ALL

SELECT 'Öðrenci Ýþleri'
FROM DUYURUCU
INNER JOIN OGRENCI_ISLERI_DUYURUCUSU ON OGRENCI_ISLERI_DUYURUCUSU.Kimlik_numarasi=DUYURUCU.Kimlik_numarasi

SELECT *
FROM DUYURU
WHERE DUYURU.Kimlik_numarasi='...'

--------------------------------------------------------------------------------------------------------------

SELECT *
FROM DUYURU 
INNER JOIN BOLUM_DUYURUCUSU ON DUYURU.Kimlik_numarasi=BOLUM_DUYURUCUSU.Kimlik_numarasi
INNER JOIN YONELIK ON YONELIK.Duyuru_id=DUYURU.Duyuru_id
WHERE YONELIK.Bolum_ismi='Bilgisayar Mühendisliði'

SELECT *
FROM DUYURU 
INNER JOIN FAKULTE_DUYURUCUSU ON DUYURU.Kimlik_numarasi=FAKULTE_DUYURUCUSU.Kimlik_numarasi
INNER JOIN YONELIK ON YONELIK.Duyuru_id=DUYURU.Duyuru_id
WHERE YONELIK.Fakulte_ismi='Mühendislik Fakültesi'

SELECT *
FROM DUYURU 
INNER JOIN OGRENCI_ISLERI_DUYURUCUSU ON DUYURU.Kimlik_numarasi=OGRENCI_ISLERI_DUYURUCUSU.Kimlik_numarasi
INNER JOIN YONELIK ON YONELIK.Duyuru_id=DUYURU.Duyuru_id
WHERE YONELIK.Bolum_ismi='Bilgisayar Mühendisliði'


